### ISSUE TITLE
Player cannot access the SkyGrid gamemode

### ISSUE THREAD

**Issue by Lmmb74** [BentoBoxWorld/SkyGrid#10]
**Description**
Whenever I execute the command /sg, my server stops responding. Not only the player does not get teleported to its new island, but also the console throws the same error until it finally crashes.

**Steps to reproduce the behavior:**
1. Execute /sg command as the user
2. Check the console

**Expected behavior**
The player gets teleported to its new island.

**Screenshots**
Not applicable. But here is the [error](https://hastebin.com/cenubucaqe.md).

**Server Information:**

 - Database being used (YAML, JSON, MySQL, MongoDB): YAML
 - OS: Windows 10 x64
 - Java Version: Java 8 (1.8.0_202)
 - BentoBox version: 1.3.0-SNAPSHOT (Build [#800](https://ci.codemc.org/job/BentoBoxWorld/job/BentoBox/800/))
 - Addons installed? 

> [17:50:08 INFO]: AcidIsland 1.3.0-SNAPSHOT
[17:50:08 INFO]: BSkyBlock 1.3.0-SNAPSHOT
[17:50:08 INFO]: Biomes 0.5.0-SNAPSHOT
[17:50:08 INFO]: Challenges 0.5.0-SNAPSHOT
[17:50:08 INFO]: Level 1.2.1-SNAPSHOT
[17:50:08 INFO]: Limits 0.1.0-SNAPSHOT
[17:50:08 INFO]: SkyGrid 0.0.3-SNAPSHOT
[17:50:08 INFO]: WelcomeWarps 1.2-SNAPSHOT

 - Other plugins?

> Plugins (4): BentoBox, LuckPerms, WorldEdit, WorldGuard

**Additional context**
I am using PaperSpigot 1.13.2 - Build 522.

**Comment by tastybento** [comment]
Thanks.
