### ISSUE TITLE
Protection settings not saving 

### ISSUE THREAD

**Issue by robert-beckley** [BentoBoxWorld/SkyGrid#13]
**Description**
Upon server restart changes made to the protection flags made in /sg settings are not saved and revert back on server restart. The one i have noticed is the trees grow outside of area flag.

**Steps to reproduce the behavior:**
1. Change flag
2. Restart server
3. flag has reverted to previous setting.

**Expected behavior**
Flag settings is applied and saved on a restart.

**Screenshots**
![image](https://user-images.githubusercontent.com/41904721/54274460-3ec91d00-45dc-11e9-89b0-6739f116452d.png)

**Server Information:**

Uhh went to give you the bbox v but got this 
![image](https://user-images.githubusercontent.com/41904721/54274540-733cd900-45dc-11e9-9fb2-d0711ef8c644.png)
Here is the addons i have and the bento box version is 1.3.1
![image](https://user-images.githubusercontent.com/41904721/54274704-e1819b80-45dc-11e9-86e2-9e73523e79f9.png)

**Additional context**

**Comment by tastybento** [comment]
Let's try and find out the problem with the version and then work from there.

**Comment by robert-beckley** [comment]
Hey, I didmt post the version error as a ticket as i know what casued it and its not an error that should come up ever/often.

As i have split bentobox over 2 servers in my network due to the performance issues of having all 4 gamemods on 1 server, i had deleted a set of worlds (CaveBlock) from one server while it was online as i had cloned them over to another server. 

As the worlds were registerd with bentobox on startup the suddon lack of worlds casued it to freak out. Now removing a world while the server is running is always a bad idea but givin the way that my network runs it was posabile as i have just sent all players and a copy of the worlds over to a parallel server.

**Comment by tastybento** [comment]
Ah, okay. I thought it was something to do with worlds being deleted mid game. I'll try and replicate that. Now, I'm not sure if this is related or not.

Anyway, let me try and replicate this. What database type are you using? I may need a copy...

**Comment by tastybento** [comment]
Just testing a fresh install does not show any issues, so it's probably something specific to your setup. Let me know what it is and if I can get a copy of the config.yml and database.

**Comment by robert-beckley** [comment]
[BBOX.zip](https://github.com/BentoBoxWorld/SkyGrid/files/2971408/BBOX.zip)

**Comment by robert-beckley** [comment]
Im still having the issue for sure. here is a /pl incase it helps

![image](https://user-images.githubusercontent.com/41904721/54436959-b5564e00-4787-11e9-83fc-b1be0b08fa5b.png)

Also the version command still errors on use even after restart (it has been days)
Both /bbox v and /bbox version error 

![image](https://user-images.githubusercontent.com/41904721/54437107-ffd7ca80-4787-11e9-8c67-954b6e01a12b.png)

**Comment by tastybento** [comment]
Yes, I fixed the version command, but it's on 1.4.0-SNAPSHOT.
 I'll have a look at your zip file this weekend.

**Comment by robert-beckley** [comment]
Awesome its a much larger file but here is a copy with the worlds too https://www.dropbox.com/s/iw7ac81w2xqjear/SKYGRIDBackup_Mar%2015%2C%202019%2004-10-50.rar?dl=0

**Comment by tastybento** [comment]
11 gigs! Haha. Okay downloading now.

**Comment by tastybento** [comment]
Okay, I'm fixing the issue with settings. 
https://github.com/BentoBoxWorld/BentoBox/issues/614
