### ISSUE TITLE
When leaving the server idle, CPU usage goes up, and the disk is written to every 1 second. 

### ISSUE THREAD

**Issue by robbiemcleod56** [BentoBoxWorld/SkyGrid#14]
**Description**
I've been having this problem ever since I set up SkyGrid, just never thought it was going to be a repeating issue. The server has all three of your working games on it (SkyBlock, AcidIsland, and SkyGrid, I couldn't get CaveBlock to work at all, at least while installed with the other games,) and noticed the odd behaviour mentioned above. I would leave the server running, and it could take it days, it could take it hours, but it always ends up stuck in some sort of loop where the CPU usage goes to about 25%-50% on my own dedicated server, and the disk can be heard being written to every second, although only a small tick sound. Also sorry, but I forgot to grab a timings report before restarting the server.

**Steps to reproduce the behavior:**
1. Just leaving it running for an extended period of time with all of the games installed. 

**Expected behavior**
Definitely not high CPU and repetitive disk usage. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7958152/54546792-cf0bb700-497a-11e9-9a9f-d0cdb6af17a8.png)

**Server Information:**
 - Spigot 1.13.2
 - 5.7.23 - MySQL Community Server
 - OS: Windows 10 1809 (Also happened on 1803)
 - CPU is Xeon E5506, quad core with no hyperthreading
 - 19GB RAM
 - Java Version: java version "1.8.0_201"
    Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
    Java HotSpot(TM) Client VM (build 25.201-b09, mixed mode, sharing)
 - BentoBox version: 1.4.0-SNAPSHOT
 - Addons installed? 
    AcidIsland 1.3.0-SNAPSHOT
    BSkyBlock 1.3.0-SNAPSHOT
    SkyGrid 1.3.0-SNAPSHOT
    Biomes 0.4.2
    Challenges 0.5.1
    Level 1.2.2-SNAPSHOT
    Limits 0.1.0-SNAPSHOT
    WelcomeWarps 1.2-SNAPSHOT
 - Other plugins? 
    BungeeServerSigns, LuckPerms, PAC, EnderPearlWorld, AntiBuild, Vault, ProtocolSupport, ProtocolLib, ProtocolSupportLegacyChest, GUIShop, BentoBox, Essentials, EssentialsChat, IslandBorder, PerWorldInventory, SuperVanish, EssentialsSpawn, BungeeTabListPlus, Multiverse-Core, AuthMe, AuthMeBridge

**Additional context**
If there's a certain log you would like, let me know. Also unrelated (kind of,) but there's a similar bug I'm posting for AcidIsland where it takes a massive amount of CPU.

**Comment by tastybento** [comment]
You should restart the server every 24 hours. Here's a typical tip from a random server hosting company I found about it: https://shockbyte.com/billing/knowledgebase/5/Tip-How-often-you-should-restart-your-Minecraft-server.html

I'd say that SkyGrid has some of the most intense memory requirements because every single block is exposed and active on that world. With regular worlds, they are typically hidden/occluded, so don't have to be managed.

**Comment by robbiemcleod56** [comment]
RAM isn't the problem, I don't hit the top of that, no crashes, nothing like that, and a player doesn't even need to connect for it to start happening. It's seemingly random. I've already noticed the RAM requirements when setting it up (hard not to notice. Haha.) But there is a loop it gets stuck in for some reason. What's the debug command? I'll try running that the next time it happens and post the log.

**Comment by robbiemcleod56** [comment]
Update: The only way I was able to fix the high CPU usage at startup from AcidIsland was to delete the entire world for that game. I'm assuming that this means that just as long as no one enters that world ever, it will never have the glitch. 
https://timings.spigotmc.org/?url=yozokojixa
