### ISSUE TITLE
Portal Teleportation

### ISSUE THREAD

**Issue by robert-beckley** [BentoBoxWorld/SkyGrid#15]
**Description**
More often than not when a player makes / locates a end/nether portal and activaties it they can not use it as the safety teleporter can not find a safe space to Teleport them to and they receive the "Error this loaction is not safe" message

**Steps to reproduce the behavior:**
1. Find / build portal
2. Activate it
3. Enter it

**Expected behavior**
To be teleported to the relative location / world upon entering the portal

**Screenshots**
![image](https://user-images.githubusercontent.com/41904721/55686400-041c8f80-59a4-11e9-9273-a0bc16a05323.png)

**Server Information:**

[Please complete the following information:]
![image](https://user-images.githubusercontent.com/41904721/55686379-d59eb480-59a3-11e9-8ff9-5e5e0364dfa4.png)

![image](https://user-images.githubusercontent.com/41904721/55686372-c0298a80-59a3-11e9-821f-15b6e736f3e2.png)

**Additional context**
This only seems to be an issues in the skygrid gamemode, We dont have players play in the island space. we do use multiverse and grief prevention. It is not all portals. We have found that making a nether portal 3 blocks wide and centered on a row of blocks in the world. 

(Not sure if you have my server files still or not but i can resend if you like)

**Comment by tastybento** [comment]
Aha. I’ll check into the this.

**Comment by tastybento** [comment]
This is occurs when a player is outside their "island" space. I made some adjustments to allow players to teleport correctly. It'll work with 1.4.x but players will not be able to teleport back from the nether via a portal (they'll need to use the /sg command). This is fixed in BentoBox 1.5.0.

**Comment by BONNe** [comment]
Probably then BentoBox should throw more specific error, not general...
f.e. in log file mention why it was not able to teleport. So admins could see reason and you could easier fix it ;)
