### ISSUE TITLE
SkyGrid per player world

### ISSUE THREAD

**Issue by TNTUP** [BentoBoxWorld/SkyGrid#17]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A skygrid world created for player A. Player B has its own Skygrid world and C is teamed up with player B. Player D has his own skygrid world. Nether/End are shared between all skygrid worlds (like it does with AcidIsland and Skyblock)

**Describe alternatives you've considered**
I don't know, lol XD

**Additional context**
I don't know the Spigot/Paper world limits, like if you have a 1k player base, 20-30 active, that would have a lot of worlds, taking space but if you have TB free space who cares? :P 

Thinking it can support up to 1.12.x to 1.14.x

**Comment by BONNe** [comment]
Space is not an issue. Issue is with game ticks.
I doubt you will be able to run more then 5 sky-grid instances at the same time.
Server will just could not process ticks in normal speed.

**Comment by TNTUP** [comment]
Oh, well... disregard this feature request! Thanks for the clarification BONNe^^
