### ISSUE TITLE
Could not pass event PlayerPortalEvent to BentoBox V1.5.1

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [BentoBoxWorld/SkyGrid#18]
**Description**
End portals not working on Skygrid (Have not tested any other addons)
**Steps to reproduce the behavior:**
1. Jump in end portal
2. View console
3. Watch text spam

**Expected behavior**
End up in the end.

**Screenshots**
Log snippet, this line occurs about 500 times on repeat.
https://pastebin.com/4edCK2Vn

**Server Information:**

[Please complete the following information:]
 - Database being used JSON
 - OS: Windows server 2008 R2 Enterprise
 - Java Version: 1.8.0_201-b09
 - BentoBox version: 1.5.1
- Addons installed?   https://i.imgur.com/3AlFkk5.png
 - Other plugins? https://i.imgur.com/fWggbdU.png

**Additional context**

**Comment by tastybento** [comment]
Thanks! This was a bug in BentoBox.
