### ISSUE TITLE
Stuck on 99%

### ISSUE THREAD

**Issue by adwm** [BentoBoxWorld/SkyGrid#19]
**Description**
When the addon starts rendering the world it get stuck at 99%

**Steps to reproduce the behavior:**
1. Start the server with out a world for skygrid and with the addon
2. Wait for it to start making the world
3. Gets stuck at 99%

**Expected behavior**
The world should finish generating

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): JSON
 - OS: Windows
 - Java Version: Java 8
 - BentoBox version: 1.5.3
 - Addons installed? just skygrid
 - Other plugins? luckperms

**Comment by tastybento** [comment]
What server version are you using?

**Comment by adwm** [comment]
1.14.2

**Comment by tastybento** [comment]
I have not tested on 1.14.x so I cannot say it is compatible yet. I'll see if there's some reason. But I do recommend you upgrade to 1.14.3 ASAP anyway.

**Comment by CyberRyan1** [comment]
Will it work on 1.13.2?

**Comment by tastybento** [comment]
Yes. Should do.

**Comment by adwm** [comment]
I plan on upgrading tomorrow as I was giving my server a little while longer to get their god armor sets but yea ill test it on 1.14.3 when I get the chance.

**Comment by tastybento** [comment]
I don't think it'll work. I read somewhere that tree spawning in the generator can cause it to go into an infinite loop so I think that's what happening.

**Comment by adwm** [comment]
so should I load the map in a 1.13.2 server and then just load it into 1.14.3 and add essentialsX and stuff?

**Comment by robert-beckley** [comment]
I have also had this issue on a fresh Install of just Bento running.

**Comment by tastybento** [comment]
I am going to look at this over the next few days and try to get 1.14 running.
