### ISSUE TITLE
Reset Ability

### ISSUE THREAD

**Issue by robert-beckley** [BentoBoxWorld/SkyGrid#2]
The ability to reset in SkyGrid, similar to SkyBlock & Acid Island

/sg reset would idealy:
 - Reset player inventory 
 - Reset the Eco balance 
 - Reset the status of any challenge 
 - Take them to a new spot on the Zone Grid 
 - If possible reset the zone they were in back to a default layout (Async / Schem?) 
 - Reset death count
- Abandon all teams

**Comment by tastybento** [comment]
Yep. Should be possible. But I expect they’ll need to leave any team first.

**Comment by tastybento** [comment]
Done.
