### ISSUE TITLE
1.14.3 Generation issues 

### ISSUE THREAD

**Issue by robert-beckley** [BentoBoxWorld/SkyGrid#21]
**Description**
Worlds not made addon disabled. 

**Steps to reproduce the behavior:**
1. start a new world on 1.14.3 spigot bento 1.6.0 Skygruid 1.5.0

**Expected behavior**
Worlds to be made.

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): JSON
 - Java Version: 10
 - BentoBox version: 1.6.0 Snapshot 
 - Addons installed? Just SkyGrid
 - Other plugins? Plugins (16): AdvancedPortals, WorldEdit, DeluxeTags, PlaceholderAPI, PermissionsEx, Vault, BungeeTabListPlus, ProtocolLib, WorldGuard, Essentials, BentoBox, HolographicDisplays, Multiverse-Core, DeluxeChat, DiscordSRV, MultiWorldMoney

**Additional context**
```
03.07 10:55:33 [Server] Server thread/INFO [BentoBox] Enabling BentoBox v1.6.0-SNAPSHOT-b1230
03.07 10:55:33 [Server] Server thread/INFO [BentoBox] Loading Settings from config.yml...
03.07 10:55:33 [Server] Server thread/INFO [BentoBox] Hooking with Vault...
03.07 10:55:33 [Server] Server thread/INFO [BentoBox] Loading addons...
03.07 10:55:34 [Server] Server thread/ERROR [BentoBox] Could not load config object! argument type mismatch
03.07 10:55:34 [Server] Server thread/ERROR [BentoBox] java.lang.IllegalArgumentException: argument type mismatch
03.07 10:55:34 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03.07 10:55:34 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
03.07 10:55:34 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03.07 10:55:34 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498)
03.07 10:55:34 [Server] INFO at world.bentobox.bentobox.database.yaml.YamlDatabaseHandler.deserializeValue(YamlDatabaseHandler.java:249)
03.07 10:55:34 [Server] INFO at world.bentobox.bentobox.database.yaml.YamlDatabaseHandler.createObject(YamlDatabaseHandler.java:233)
03.07 10:55:34 [Server] INFO at world.bentobox.bentobox.database.yaml.YamlDatabaseHandler.loadObject(YamlDatabaseHandler.java:128)
03.07 10:55:34 [Server] INFO at world.bentobox.bentobox.api.configuration.Config.loadConfigObject(Config.java:64)
03.07 10:55:34 [Server] INFO at world.bentobox.bentobox.api.configuration.Config.loadConfigObject(Config.java:81)
03.07 10:55:34 [Server] INFO at world.bentobox.skygrid.SkyGrid.loadSettings(SkyGrid.java:43)
03.07 10:55:34 [Server] INFO at world.bentobox.skygrid.SkyGrid.onLoad(SkyGrid.java:39)
03.07 10:55:34 [Server] INFO at world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:122)
03.07 10:55:34 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
03.07 10:55:34 [Server] INFO at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
03.07 10:55:34 [Server] INFO at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
03.07 10:55:34 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
03.07 10:55:34 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
03.07 10:55:34 [Server] INFO at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
03.07 10:55:34 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
03.07 10:55:34 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
03.07 10:55:34 [Server] INFO at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
03.07 10:55:34 [Server] INFO at world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:75)
03.07 10:55:34 [Server] INFO at world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:159)
03.07 10:55:34 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
03.07 10:55:34 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
03.07 10:55:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
03.07 10:55:34 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458)
03.07 10:55:34 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372)
03.07 10:55:34 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:195)
03.07 10:55:34 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:760)
03.07 10:55:34 [Server] INFO at java.lang.Thread.run(Thread.java:748)
03.07 10:55:34 [Server] Server thread/ERROR [BentoBox] [SkyGrid] SkyGrid settings could not load! Addon disabled.
03.07 10:55:34 [Server] Server thread/ERROR [BentoBox] Skipping SkyGrid due to an unhandled exception...
03.07 10:55:34 [Server] Server thread/ERROR [BentoBox] java.lang.NullPointerException
03.07 10:55:34 [Server] INFO at world.bentobox.skygrid.generators.WorldStyles.normalWorldProbabilities(WorldStyles.java:67)
03.07 10:55:34 [Server] INFO at world.bentobox.skygrid.generators.WorldStyles.<init>(WorldStyles.java:31)
03.07 10:55:34 [Server] INFO at world.bentobox.skygrid.SkyGrid.loadSettings(SkyGrid.java:50)
03.07 10:55:34 [Server] INFO at world.bentobox.skygrid.SkyGrid.onLoad(SkyGrid.java:39)
03.07 10:55:34 [Server] INFO at world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:122)
03.07 10:55:34 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
03.07 10:55:34 [Server] INFO at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
03.07 10:55:34 [Server] INFO at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
03.07 10:55:34 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
03.07 10:55:34 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
03.07 10:55:34 [Server] INFO at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
03.07 10:55:34 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
03.07 10:55:34 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
03.07 10:55:34 [Server] INFO at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
03.07 10:55:34 [Server] INFO at world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:75)
03.07 10:55:34 [Server] INFO at world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:159)
03.07 10:55:34 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
03.07 10:55:34 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
03.07 10:55:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
03.07 10:55:34 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458)
03.07 10:55:34 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372)
03.07 10:55:34 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:195)
03.07 10:55:34 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:760)
03.07 10:55:34 [Server] INFO at java.lang.Thread.run(Thread.java:748)
03.07 10:55:34 [Server] Server thread/INFO [BentoBox] Loaded 0 addons.
```

**Comment by tastybento** [comment]
Similar or same as #19

**Comment by robert-beckley** [comment]
Similar but not exactly. as mine doesn't get stuck I get an error and bento progress.

**Comment by tastybento** [comment]
Yes, this seems to be related to the config.yml not being able to be loaded. Hmm. Could you try with the latest version and see if a clean install still has a problem for you?

**Comment by robert-beckley** [comment]
I will try on a blank server soon and give you the steps taken and issues that occur.

**Comment by robert-beckley** [comment]
Okay so. 
I used a fresh server and a fresh bento install using Bento build 1231 (1.6.0) 
Used latest sky grid build 126 (1.6.0)
Had the following plugins 
![image](https://user-images.githubusercontent.com/41904721/60636468-eef7b580-9e59-11e9-854c-bebe16514486.png)
Used the latest build of spigot built today (1.14.3) 
and it all loaded up fine 
i made a new world and edited the config to my liking and it has the error 

04.07 12:53:46 [Server] Server thread/INFO [BentoBox] Enabling BentoBox v1.6.0-SNAPSHOT-b1231
04.07 12:53:46 [Server] Server thread/INFO [BentoBox] Loading Settings from config.yml...
04.07 12:53:47 [Server] Server thread/INFO [BentoBox] Hooking with Vault...
04.07 12:53:47 [Server] Server thread/INFO [BentoBox] Loading addons...
04.07 12:53:47 [Server] Server thread/ERROR [BentoBox] Could not load config object! argument type mismatch
04.07 12:53:47 [Server] Server thread/ERROR [BentoBox] java.lang.IllegalArgumentException: argument type mismatch
04.07 12:53:47 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04.07 12:53:47 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
04.07 12:53:47 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04.07 12:53:47 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498)
04.07 12:53:47 [Server] INFO at world.bentobox.bentobox.database.yaml.YamlDatabaseHandler.deserializeValue(YamlDatabaseHandler.java:249)
04.07 12:53:47 [Server] INFO at world.bentobox.bentobox.database.yaml.YamlDatabaseHandler.createObject(YamlDatabaseHandler.java:233)
04.07 12:53:47 [Server] INFO at world.bentobox.bentobox.database.yaml.YamlDatabaseHandler.loadObject(YamlDatabaseHandler.java:128)
04.07 12:53:47 [Server] INFO at world.bentobox.bentobox.api.configuration.Config.loadConfigObject(Config.java:64)
04.07 12:53:47 [Server] INFO at world.bentobox.bentobox.api.configuration.Config.loadConfigObject(Config.java:81)
04.07 12:53:47 [Server] INFO at world.bentobox.skygrid.SkyGrid.loadSettings(SkyGrid.java:43)
04.07 12:53:47 [Server] INFO at world.bentobox.skygrid.SkyGrid.onLoad(SkyGrid.java:39)
04.07 12:53:47 [Server] INFO at world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:122)
04.07 12:53:47 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
04.07 12:53:47 [Server] INFO at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
04.07 12:53:47 [Server] INFO at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
04.07 12:53:47 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
04.07 12:53:47 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
04.07 12:53:47 [Server] INFO at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
04.07 12:53:47 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
04.07 12:53:47 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
04.07 12:53:47 [Server] INFO at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
04.07 12:53:47 [Server] INFO at world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:75)
04.07 12:53:47 [Server] INFO at world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:159)
04.07 12:53:47 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
04.07 12:53:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
04.07 12:53:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
04.07 12:53:47 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:460)
04.07 12:53:47 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:374)
04.07 12:53:47 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:195)
04.07 12:53:47 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:764)
04.07 12:53:47 [Server] INFO at java.lang.Thread.run(Thread.java:748)
04.07 12:53:47 [Server] Server thread/ERROR [BentoBox] [SkyGrid] SkyGrid settings could not load! Addon disabled.
04.07 12:53:47 [Server] Server thread/ERROR [BentoBox] Skipping SkyGrid due to an unhandled exception...
04.07 12:53:47 [Server] Server thread/ERROR [BentoBox] java.lang.NullPointerException
04.07 12:53:47 [Server] INFO at world.bentobox.skygrid.generators.WorldStyles.normalWorldProbabilities(WorldStyles.java:67)
04.07 12:53:47 [Server] INFO at world.bentobox.skygrid.generators.WorldStyles.<init>(WorldStyles.java:31)
04.07 12:53:47 [Server] INFO at world.bentobox.skygrid.SkyGrid.loadSettings(SkyGrid.java:50)
04.07 12:53:47 [Server] INFO at world.bentobox.skygrid.SkyGrid.onLoad(SkyGrid.java:39)
04.07 12:53:47 [Server] INFO at world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:122)
04.07 12:53:47 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
04.07 12:53:47 [Server] INFO at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
04.07 12:53:47 [Server] INFO at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
04.07 12:53:47 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
04.07 12:53:47 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
04.07 12:53:47 [Server] INFO at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
04.07 12:53:47 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
04.07 12:53:47 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
04.07 12:53:47 [Server] INFO at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
04.07 12:53:47 [Server] INFO at world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:75)
04.07 12:53:47 [Server] INFO at world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:159)
04.07 12:53:47 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
04.07 12:53:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
04.07 12:53:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
04.07 12:53:47 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:460)
04.07 12:53:47 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:374)
04.07 12:53:47 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:195)
04.07 12:53:47 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:764)
04.07 12:53:47 [Server] INFO at java.lang.Thread.run(Thread.java:748)
04.07 12:53:47 [Server] Server thread/INFO [BentoBox] Loaded 0 addons.

Something in my config is doing it

**Comment by robert-beckley** [comment]
[Madeitazipasgithubisdumbandwonttakeaymlfileconfig.zip](https://github.com/BentoBoxWorld/SkyGrid/files/3357441/Madeitazipasgithubisdumbandwonttakeaymlfileconfig.zip)

**Comment by robert-beckley** [comment]
I figured it out and I feel dumb 
  chest-fill:
    # Chest fill setting. 1 = normal, 0 = nothing, 1+ for more items
    overworld: 1
    # Nether chest fill setting
    nether: 1
    # The End chest fill setting
    end: 1

I set it to "1+" and that's what was doing it the wording threw me off im assuming its meant to be 2,3,4, etc not 1+ aha

**Comment by tastybento** [comment]
Oh wow! I never thought of that! I'll change the wording of the comment.
