### ISSUE TITLE
Certain blocks don't update

### ISSUE THREAD

**Issue by Alexis-Grimm** [BentoBoxWorld/SkyGrid#23]
I recently started a private server for me and my friends to play skygrid, we just reached the point where we could build what is essentially a cobblestone generator, now i could not find any config options relating to this problem in any plugin or addon we are using. Up til this point we still have not been able to grow trees, for many days, and water and lava buckets that we place will not flow in any direction except down.
We are currently using bentobox 1.5.3 and skygrid 1.6.0

**Comment by tastybento** [comment]
I suspect what is happening here is that the protection flags for when you are outside your protected area are kicking in. If you are inside your protected area I suspect it should work. 

I need to fix this bug but here's a workaround:

To fix, you need to upgrade to the latest 1.6.0 Bentobox and then set the world flags in SkyGrid's config.yml to allow this. We have a PR pending to enable these settings via GUI, but for now you need to add them manually:

```
flags:
   LIQUIDS_FLOWING_OUT: true
   TREES_GROWING_OUTSIDE_RANGE: true
```

**Comment by Alexis-Grimm** [comment]
That worked thank you.

**Comment by Alexis-Grimm** [comment]
Wait i can't find the 1.6.0 version of bentobox, just 1.5.3?

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/BentoBox#downloads

**Comment by tastybento** [comment]
I'm planning to release 1.6.0
