### ISSUE TITLE
SkyGrid Corrupts its own Config

### ISSUE THREAD

**Issue by InfinityAspire** [BentoBoxWorld/SkyGrid#24]
**Description**
When using BentoBox & SkyGrid 1.6.0, on server restarts it corrupts it's own config resulting in possible world corruption and the config resetting.

**Steps to reproduce the behavior:**
1. Install BentoBox and SkyGrid Release Version 1.6.0
2. Have a single person go to their own grid
3. Reboot server
4. Check config and worlds for corruption.

**Expected behavior**
The plugin to, well, work 

**Server Information:**
 - YAML
 - Ubuntu 16
 - Java Version: Java 12
 - Server Version: PaperSpigot 1.14.4
 - BentoBox version: 1.6.0
 - Addons installed? SkyGrid-1.6.0
 - Other plugins? CMI

**Additional context**
It also always errors on the first /sg that's run. A second /sg by the same player will correctly teleport them to the grid, however if a second person tries to run the command it freezes the server.

Setting the config to read only stops the world and config corruption, however the secondary error [above this sentence] always occurs no matter what.

**Comment by tastybento** [comment]
What’s the error? Can you share from the console? Also, just double checking - are you using YAML?

**Comment by tastybento** [comment]
Never mind, I've replicated this.

**Comment by tastybento** [comment]
Okay, this is really weird. I saw a corrupted config so I started trying older builds and it all worked. Then I got to the latest and it still works. This is on a clean install. I'm not sure what the issue is. Did you download SkyGrid from the release tab of this project or the CI server?

**Comment by InfinityAspire** [comment]
Both BentoBox and SkyGrid were downloaded from the release tab for 1.6.0 on both

**Comment by BONNe** [comment]
Could you write in game or console ./bentobox v
As it will provide information about initialized addons. More information for us.

**Comment by InfinityAspire** [comment]
At work at the moment, will do when I'm home

**Comment by InfinityAspire** [comment]
[Loaded Addons Screenshot](http://prntscr.com/ouqude)

**Comment by InfinityAspire** [comment]
As a side note, when I set the config to read only, BentoBox consistently complained that it couldn't write to it. Which I don't know if it's supposed to be doing but realistically I don't think playerdata is supposed to be saved in the config, but the database instead

**Comment by tastybento** [comment]
BentoBox saves settings to the config.yml - that's normal. It'll do that to keep it up to date with the latest settings and also write world-specific settings, such a flags. Player data is not stored there. During the initial loading it'll save all the default flags to the config, so there's going to be multiple saves.

If you write protect config.yml, does everything work fine? 
If you do not write protect it, what errors do you see in the console log and what does the config.yml become?

**Comment by InfinityAspire** [comment]
If I write protect it the world loads correctly but the /sg command errors and BentoBox complains it couldn't write to the config when running /sg.
This error is: [https://i.imgur.com/LBrRRLy.png](https://i.imgur.com/LBrRRLy.png)

If I don't write protect it, it fills with a metric ton of "Comment: <some form of uuid string>" then on next reboot it complains it couldn't read the config and makes a new one.

**Comment by InfinityAspire** [comment]
I should add that that error stacktrace runs either way, write protected or not.

**Comment by tastybento** [comment]
That SkyGrid version doesn't look right. Just to check, can you download the latest version from the CI server and try that: https://ci.codemc.org/job/BentoBoxWorld/job/SkyGrid/

**Comment by InfinityAspire** [comment]
Doesn't seem to corrupt or error using 1.7.0 of SkyGrid, perhaps the jar on the release page is broken.

Although now when a second player does /sg the server freezes up to the point where everyone is kicked and this spams [https://i.imgur.com/32nPDYz.png](https://i.imgur.com/32nPDYz.png)

**Comment by InfinityAspire** [comment]
Also, the permissions that are supposed to be true by default, aren't set. At least skygrid.skygrid.go isn't

**Comment by InfinityAspire** [comment]
Yeah it's 100% freezing the server when loading a new part of the world

**Comment by BONNe** [comment]
Permission could be skygridskygrid.go

**Comment by InfinityAspire** [comment]
That's what I said, it's not set by default even though the wiki says it is. Also I've allocated 6GB of RAM to try and alleviate the server freezing but it still hangs and boots everyone every time a new player runs /sg, I'm assuming because of terrain gen

**Comment by tastybento** [comment]
Can you share the actual crash log text because I can’t read the screenshot. The full log in in your server folder. 
Now that the config isn’t crashing, I recommend you stop the server and delete all the SkyGrid world. Also, don’t change any config settings right now. 
I’ll check the permissions thing.

**Comment by InfinityAspire** [comment]
At work again, will get log as soon as I can.
I did delete everything SkyGrid related before trying 1.7.0

**Comment by tastybento** [comment]
Understood - I need to head off to work now too.
If the world gen is taking too long then it could be that the watch dog timer on the server is just a little too short. That can be set in the server.properties file. Anyway, it'd be good to see the crash files for sure. Thanks.

**Comment by InfinityAspire** [comment]
The timeout time is already set to 60 seconds in the Spigot YML.
It's not a setting I've ever changed.
Do you still need the log?

**Comment by tastybento** [comment]
Yes, please share the log. The log [here](https://m.imgur.com/32nPDYz) on the second line says 15 seconds so i’m not sure where that is coming from.

**Comment by InfinityAspire** [comment]
Paper has a built in warning after 15 seconds but the actual timer in Spigot it set to 60, will share the log when I'm home

**Comment by InfinityAspire** [comment]
Okay, so the latest Paper commits have fixed the immense lag on loading, however all gravity blocks now fall on generation and the lava/water blocks flow around before being updated by players

**Comment by InfinityAspire** [comment]
Scratch that last completely, it was fixed for a hot second.
Link to log: [https://pastebin.com/EPCvQZ7d](https://pastebin.com/EPCvQZ7d)
This log is what occurs every time a brand new player runs /sg
The server will freeze, kick all players to compensate, then when the player rejoins and runs /sg it works.

**Comment by tastybento** [comment]
Okay. I see it’s to do with the safe spot teleport routine. Just to confirm, is the SkyGrid co dig the default? No changes?

**Comment by InfinityAspire** [comment]
It's the default bar me changing the protection size to 200.
It's also worth noting I have a Spawn world that players start in, when they run sg they are changing world's.

**Comment by tastybento** [comment]
Okay. So a quick work around is to lower the protection area to 50 again. In the case of SkyGrid, the players can still interact fully with blocks outside their area, but they have the 100 x 100 blocks to themselves. The reason the server is timing out is because the safe spot teleporting algorithm is having a hard time finding a spot to place the player and so resorts to doing a full protected area scan and with a 400 x 400 block area it craps out. I'll see if I can optimize it to do better.

**Comment by InfinityAspire** [comment]
Am I able to change this mid-game? As I have a few well established players already

**Comment by tastybento** [comment]
Yes. By the way, once a suitable home location is found, things should be stable as it’s remembered. 
I am away this weekend but this has made me think about changing how I do new players on SG. I think there’s an efficient solution involving blueprints. For now, just keep the protection area small until the player has a home.
