### ISSUE TITLE
Error When using /skygrid

### ISSUE THREAD

**Issue by thunderlight411** [BentoBoxWorld/SkyGrid#25]
**Description**
when using /skygrid to get a island or go to the skygrid the server gives one big error.
In chat you get back "An Internal Error Occurred while attempting to perform this Command"

**Steps to reproduce the behavior:**
/skygrid in game to produce the error

**Expected behavior**
Creating or teleporting the player to there skygrid

**Screenshots**
https://i.imgur.com/esKY6Kj.png

**Server Information:**
https://gist.github.com/thunderlight411/3a89fd7b498d0a98a9cd8465d8df4977
[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): JSON
 - OS: CentOS 8
 - Java Version: Java 8
 - BentoBox version: 1.6.0
 - Addons installed? 
23.08 20:24:11 [Server] INFO Running PAPER 1.14.4.
23.08 20:24:11 [Server] INFO BentoBox version: 1.6.0
23.08 20:24:11 [Server] INFO commands.bentobox.version.database
23.08 20:24:11 [Server] INFO Loaded Game Worlds:
23.08 20:24:11 [Server] INFO acidisland_world (AcidIsland): Overworld, Nether, End
23.08 20:24:11 [Server] INFO bskyblock_world (BSkyBlock): Overworld, Nether, End
23.08 20:24:11 [Server] INFO caveblock-world (CaveBlock): Overworld, Nether, End
23.08 20:24:11 [Server] INFO skygrid-world (SkyGrid): Overworld, Nether, End
23.08 20:24:11 [Server] INFO Loaded Addons:
23.08 20:24:11 [Server] INFO AcidIsland 1.6.0 (ENABLED)
23.08 20:24:11 [Server] INFO Biomes 1.5.2.1-SNAPSHOT-b129 (ENABLED)
23.08 20:24:11 [Server] INFO BSkyBlock 1.6.0 (ENABLED)
23.08 20:24:11 [Server] INFO CaveBlock 1.6.0 (ENABLED)
23.08 20:24:11 [Server] INFO Challenges 0.8.0-SNAPSHOT-#323 (ENABLED)
23.08 20:24:11 [Server] INFO Greenhouses 0.3.2-SNAPSHOT (ENABLED)
23.08 20:24:11 [Server] INFO Level 1.6.0 (ENABLED)
23.08 20:24:11 [Server] INFO MagicCobblestoneGenerator 1.5.0.1 (ENABLED)
23.08 20:24:11 [Server] INFO SkyGrid 1.6.0 (ENABLED)
23.08 20:24:11 [Server] INFO WelcomeWarps 1.6.0-SNAPSHOT-b170 (ENABLED)
 - Other plugins? 
23.08 20:25:06 [Server] INFO Plugins (31): AsyncWorldEdit, BannerBoard*, BentoBox, BossShopPro, BungeeTabListPlus*, BuycraftX, ChestSort, CMI, CMIEInjector*, CoreProtect, dynmap*, IPWhitelist*, JustEssentials, JustRank, LuckPerms, mcMMO, MorphRedeem, MultiChatSpigot, PerWorldInventory, PlaceholderAPI*, Plan, ProtocolLib*, TitleAPI, TokenManager, UltimateVotes, Vault, ViaVersion*, WorldEdit, WorldEditGlobalizerBukkit*, WorldEditSUI, WorldGuard

**Additional context**
https://gist.github.com/thunderlight411/3a89fd7b498d0a98a9cd8465d8df4977

**Comment by tastybento** [comment]
Looks like your Skygrid and BentoBox versions are not matched. Check they are both 1.6.0

**Comment by tastybento** [comment]
There was a bad release of SkyGrid. Please download latest file or use latest version on CI server
https://ci.codemc.org/job/BentoBoxWorld/job/SkyGrid/
