### ISSUE TITLE
In some edge cases, players are still put in SPECTATOR

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/SkyGrid#27]
back

Tried it with a user that never played before on the server, and they have no perms besides the default.

skygrid reset, .. they go into spectator mode and dont return from it.

_Originally posted by @mrfloris in https://github.com/BentoBoxWorld/BentoBox/issues/920#issuecomment-525242013_

**Comment by tastybento** [comment]
SkyGrid has its own reset command because it doesn't paste islands. It's out of date and needs updating.

**Comment by tastybento** [comment]
I shifted to using the Bentobox command instead.
