### ISSUE TITLE
SkyGrid Generate Platform

### ISSUE THREAD

**Issue by rackgaming** [BentoBoxWorld/SkyGrid#35]
What I mean by this is, on performium, they have it to where a new skygrid is generated(Which I'm using islandborder for that atm) and instead of users spawning on just 1 block, a platform is generated around them(they have glass around their spawn about 5-10 pieces of it) so when they do /sg or /sg reset for a new skygrid, they don't fall right away or have a better chance of survival, would just make the skygrid more user friendly seeing that it's a public server.

**Comment by tastybento** [comment]
Okay. I just added blueprints to the addon. You can now change the default blueprint bundle to use another blueprint you make. So you can make a platform if you like. Default is a bedrock block.

**Comment by rackgaming** [comment]
I'm a little confused on what you mean? I don't spawn on a bedrock block.

**Comment by rackgaming** [comment]
This should not be closed as there is no command to change blueprints for skygrid, only bskyblock

**Comment by tastybento** [comment]
You need to use the latest snapshot of Skygrid from the CI server or wait for the release of 1.10.0. 
Then use the command `/sgadmin blueprint pos1/pos2/copy/save etc.` (Or `/sga bp`) to make blueprint and set it as the default. 
I’ll leave this open so you can ask questions.

**Comment by rackgaming** [comment]
I have the 1.10 version but if a player makes their own new skygrid in the same skygrid world, when a player does /sg and picks that bundle, is it supposed to land them on the same platform or are they supposed to land on the same platform in a different area?

**Comment by tastybento** [comment]
I missed the reset command usage. The latest version will have that working now.

Everyone is in the SkyGrid world. When a new player does /sg, (or a player resets) they will go to a new spot away from other players. They will arrive on a block, which by default will be bedrock now. If you create a platform for them and make a blueprint and then set it as the default blueprint in the default bundle for the normal world, then that should work.

**Comment by rackgaming** [comment]
That worked perfectly, thank you for your patience and your amazing plugin and help.
