### ISSUE TITLE
Player can not do /skygrid with permissions

### ISSUE THREAD

**Issue by Fowleyy** [BentoBoxWorld/SkyGrid#37]
Hello, 
on my server when player want to skygrid, he cant do /skygrid and he has permissions skygrid.skygrid

**Comment by tastybento** [comment]
Okay, weird. Can Ops do it?

Do `bbox v` in console and share the results. Perms should be given automatically - you don't need to give them manually. To start a new skygrid, players should have the `skygrid.island.create` perm, but again, they should have that by default anyway.

**Comment by Godlycreations** [comment]
I am having this same issue, Ops can use the /skygrid command, but players cannot. I have added the following perms to my users:

skygrid.island.ban	
skygrid.island.expel	
skygrid.island.home	
skygrid.island.language
skygrid.island.name	
skygrid.island.reset	
skygrid.island.sethome	
skygrid.island.settings	
skygrid.island.spawn	
skygrid.island.team	
skygrid.island.team.coop	
skygrid.island.team.trust	
skygrid.settings.*	
skygrid.skygrid	

They can use all the other commands, just not the base command "/skygrid" or the command "/skygrid go" if there is any additional information that you need, please ask.

**Comment by Godlycreations** [comment]
For those that encounter this issue, add the permission "skygrid.skygrid.go" to your permissions plugin and the problem is solved. Many thanks to the members on the discord team that helped me find the missing permission that is not shown on the wiki.

**Comment by tastybento** [comment]
The permission should be given by default and it wasn't, so I just added it. Thanks!
