### ISSUE TITLE
World Generation 

### ISSUE THREAD

**Issue by BobbyTowers** [BentoBoxWorld/SkyGrid#38]
- Database being used: None
 - OS: Windows 7
 - Java Version: Java 8
 - BentoBox version: 1.92
 - Addons installed? SkyGrid
 - Other plugins? None
 - Server: Spigot 1.15.1

Everything loads fine but it doesn't generate the SkyGrid world, it justs make a standard one.

**Comment by tastybento** [comment]
Can you do `bbox v` in the console and copy and paste the result here?

**Comment by BobbyTowers** [comment]
https://pastebin.com/7YWz5T0t

**Comment by BONNe** [comment]
Did you set it up as only skygrid world (by setting it as default world in server.properties)?
As if so, then there are missing generator properties... 
https://github.com/BentoBoxWorld/BentoBox/wiki/Set-a-BentoBox-world-as-the-server-default-world

**Comment by BobbyTowers** [comment]
I got it. Thank you @BONNe
