### ISSUE TITLE
Sky grid map limit 190 blocks after spawn, superflat after that !

### ISSUE THREAD

**Issue by carlitototo** [BentoBoxWorld/SkyGrid#41]
Hey,
It's probably just me being a noob at creating servers and the solution is evident, but here is my issue !
I did a server with the bentobox/skygrid addons, and, after 2h30min of slowly doing our things, we discovered that only the first 190 blocks nearest to the spawn are sky grid, the rest is a flat world ! Do you know how to set the skygrid to be larger ? 

Thanks !

**Comment by tastybento** [comment]
Hmm. Have a look at this FAQ answer: https://github.com/BentoBoxWorld/BentoBox/wiki#i-am-getting-super-flat-after-a-while-help

Once you work out what is causing the problem, let me know. Also, you'll need to use the admin settings fix super flat (/sgadmin settings) to fix the super flat. Once you have it all fixed then turn it off because it can lag the server.

**Comment by carlitototo** [comment]
Got a look at the FAQ, wish I looked at it before, turns out I had to rename my world to skygrid in the server properties file, and the use /skygrid:skygrid to tp to the skygrid world ! 
So there are actually 2 sets of worlds, the normal one and the skygrid one ! 
Do you know what is the command to go back to the overworld ? Tried a few commands but nothing will do :/ 

Thanks, SG is amazing !

**Comment by BONNe** [comment]
BentoBox plugin manages only worlds which it creates. It tries not to affect other worlds at all.
So there are no commands that could transfer you back.
However, you can use different plugins for that, like MultiVerse, that allows teleport between worlds or using CMI, like essentials, that have global spawn location.

**Comment by tastybento** [comment]
In a pinch, I have found that the teleport command, e.g., `tp 0 120 0 tastybento` put in the **console** will teleport a player back to the main world - in that case to coordinates 0 120 0. I do a lot of testing with minimal installs so I don't always have Multiverse or other plugins installed to teleport around worlds.

Is this ticket closable now? Did you solve your problem?

**Comment by carlitototo** [comment]
Yep, the problem is solved, the ticket is closable :) Thanks for the advice, I'll try and tweak with the multiverse a little :)
