### ISSUE TITLE
Great plugin,Can I transport it to Chinese Minecraft website www..mcbbs.net?

### ISSUE THREAD

**Issue by 2173204318** [BentoBoxWorld/SkyGrid#42]
Great plugin,Can I transport it to Chinese Minecraft website www..mcbbs.net?

**Comment by Poslovitch** [comment]
Hi, sure. However, I'm quite sure it's available there already (remember that BentoBox is the actual plugin, addons like SkyGrid are just some side stuff), as multiple people have been requesting this lately.
