### ISSUE TITLE
I cant make the grid

### ISSUE THREAD

**Issue by ThatOneSupergirl** [BentoBoxWorld/SkyGrid#43]
I am trying to use the plugin for my server but it is not working? what is the command to create the grid

**Comment by BONNe** [comment]
First of all, this is not a plugin.
Just an addon for BentoBox plugin.

Here is a tutorial on how to install BentoBox and its addons:
https://bentobox-world.readthedocs.io/en/latest/BentoBox/Install-Bentobox/

And here is a general SkyGrid docs: 
https://bentobox-world.readthedocs.io/en/latest/gamemodes/SkyGrid/

By default it should be `/skygrid`, but that can be changed in config.
