### ISSUE TITLE
1.16.2 Server crashes while skygrid is generating user's world

### ISSUE THREAD

**Issue by TheOGSlayered** [BentoBoxWorld/SkyGrid#45]
Updated my spigot server to 1.16.2. Players who already had existing skygrid worlds had no effect on the server, however players who try to create a new skygrid would crash the server. 

Update to 1.16.2, have a player who has never run skygrid to type /skygrid, server will crash on world generation.

**Expected behavior**
Well, the server not crashing is the expected behaviour :P

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): yaml
 - OS: ubuntu 20.04
 - Java Version: openjava 14
 - BentoBox version: 1.14.2, 
 - Addons installed? All the addons, all the newest release, skygrid 1.14.1
 - Multiverse family of plugins, essentialsx, worldedit, and worldguard. luckperms+vault
[crash-2020-08-15_19.57.14-server.txt](https://github.com/BentoBoxWorld/SkyGrid/files/5081923/crash-2020-08-15_19.57.14-server.txt)

**Comment by tastybento** [comment]
It’s a server bug, unfortunately. Rebuild the server jar and maybe they have fixed it, or wait to upgrade to 1.16.2 until it is more stable.

**Comment by tastybento** [comment]
I just tried SkyGrid with a new build of Spigot today and it all works fine.
