### ISSUE TITLE
Teleporting to end make you fall in void skygrid version 1.18

### ISSUE THREAD

**Issue by doragoncraft** [BentoBoxWorld/SkyGrid#58]
### Expected behavior

go into portal and be at the top of the grid in the end

### Observed/Actual behavior

go into portal and you are tp to the void

### Steps/models to reproduce

https://youtu.be/CK6bgwAM3ms  (not my video from #48 but does the same thing 

### BentoBox version

25.12 20:39:46 [PebbleHost]  C*********n@gmail.com ran command: bbox version
25.12 20:39:46 [Server] [INFO] Running PAPER 1.19.
25.12 20:39:46 [Server] [INFO] BentoBox version: 1.21.1
25.12 20:39:46 [Server] [INFO] Database: JSON
25.12 20:39:46 [Server] [INFO] Loaded Game Worlds:
25.12 20:39:46 [Server] [INFO] acidisland_world (AcidIsland): Overworld, Nether, The End
25.12 20:39:46 [Server] [INFO] bskyblock_world (BSkyBlock): Overworld, Nether, The End
25.12 20:39:46 [Server] [INFO] caveblock-world (CaveBlock): Overworld, Nether, The End
25.12 20:39:46 [Server] [INFO] oneblock_world (OneBlock): Overworld, Nether, The End
25.12 20:39:46 [Server] [INFO] skygrid-world (SkyGrid): Overworld, Nether, The End
25.12 20:39:46 [Server] [INFO] Loaded Addons:
25.12 20:39:46 [Server] [INFO] AcidIsland 1.16.0 (ENABLED)
25.12 20:39:46 [Server] [INFO] AOneBlock 1.11.0 (ENABLED)
25.12 20:39:46 [Server] [INFO] Bank 1.4.0 (ENABLED)
25.12 20:39:46 [Server] [INFO] Biomes 2.0.0 (ENABLED)
25.12 20:39:46 [Server] [INFO] Boxed 1.2.1 (DISABLED)
25.12 20:39:46 [Server] [INFO] BSkyBlock 1.16.0 (ENABLED)
25.12 20:39:46 [Server] [INFO] CaveBlock 1.16.0 (ENABLED)
25.12 20:39:46 [Server] [INFO] Challenges 1.0.0 (ENABLED)
25.12 20:39:46 [Server] [INFO] ControlPanel 1.13.0 (ENABLED)
25.12 20:39:46 [Server] [INFO] DimensionalTrees 1.6.0 (ENABLED)
25.12 20:39:46 [Server] [INFO] InvSwitcher 1.11.0 (ENABLED)
25.12 20:39:46 [Server] [INFO] IslandFly 1.9.0 (ENABLED)
25.12 20:39:46 [Server] [INFO] Level 2.9.0 (ENABLED)
25.12 20:39:46 [Server] [INFO] Likes 2.3.0 (ENABLED)
25.12 20:39:46 [Server] [INFO] SkyGrid 1.18.0 (ENABLED)
25.12 20:39:46 [Server] [INFO] Visit 1.4.0 (ENABLED)
25.12 20:39:46 [Server] [INFO] Warps 1.12.0 (ENABLED)

### Plugin list

[PebbleHost] C*********n@gmail.com ran command: pl
25.12 20:40:50 [Server] [INFO] Plugins (37): AdvancedOreGen, AncientGates, AutoCraft, BentoBox, Bookshelf, ChristmasMonsters, CleanroomGenerator, CoreProtect, CratesPlus, DCSleep, DeluxeHub, DoragonSimpleBackpacks, dynmap, Essentials, EssentialsDiscord, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), floodgate, Geyser-Spigot, HeadDatabase, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, PlaceholderAPI, PlotSquared, PluginManager, Signs*, SilkSpawners_v2, Skript, SmoothTimber, Vault, ViaVersion, Vote*, WorldBorder, WorldEditSelectionVisualizer, WorldGuard

**Comment by tastybento** [comment]
In the SkyGrid config.yml around line 1031 make this setting:

```create-obsidian-platform: true```

This should be the default but it's not and so you drop into the void. I'll fix this but you can set it yourself so you don't have this issue.
