### ISSUE TITLE
Enable weight based chest loot generation for skygrid

### ISSUE THREAD

**Issue by Doomsdoor** [BentoBoxWorld/SkyGrid#62]
### Is your feature request related to a problem?

Skygrid nether chests have few items available to generate so valuable items like elytra and netherite ingots spawn very commonly because they have the same drop rate as the other items

### Describe the solution you'd like.

Make the items weight based like block generation so you can alter rarity of loot items inside chests

### Describe alternatives you've considered.

I couldn't think of a simpler method to fix the issue

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
This is done. Download the snapshot from ci.bentobox.world to try it. You will need to delete the old config.yml to enable the box probabilities to be created in a new one.
