### ISSUE TITLE
When using SkyGrid, portal well is generated below `y = 0`

### ISSUE THREAD

**Issue by FreeMonoid** [BentoBoxWorld/SkyGrid#63]
### Expected behavior

Whole portal frame should be generated above `y = 0`

### Observed/Actual behavior

Bottom half of the portal tries to be generated below `y = 0`, making it disappear:
![2023-12-23_00 46 26](https://github.com/BentoBoxWorld/SkyGrid/assets/49086127/bc7561d2-0798-428c-8d9e-e21d301c83be)

### Steps/models to reproduce

1. Add SkyGrid
2. Ensure `battle.start-on-join: true`
3. Join SkyGrid End island (that is not at 0,0)

### BentoBox version

> version
[00:43:06 INFO]: Current: git-Purpur-2095 (MC: 1.20.2)
> version BentoBox
[00:43:11 INFO]: BentoBox version 1.24.1
> version BentoBox-SkyGrid
[00:43:15 INFO]: BentoBox-SkyGrid version 1.19.0

### Other

Originally [reported on Discord](https://discord.com/channels/272499714048524288/310623455462686720/1187874961747087480)

**Comment by tastybento** [comment]
I added config to enable you to set the height where you want and shifted to default to a height of 3. You can download the snapshot from ci.bentobox.world and see if that works for you.
