### ISSUE TITLE
SkyGrid Custom Loot Tables 

### ISSUE THREAD

**Issue by robert-beckley** [BentoBoxWorld/SkyGrid#7]
A way to set the loot that is generated in the chest throughout the world. 

Either in the config.yml or a sperate loot.yml 

Ability to define based on world (End Nether Overworld) 

Set the max different items in a chest 

List Based on a chance ratio of spawning in a chest
MATERIALID : STACKAMOUNT : CHANCE
STONE:32:20
DIRT:16:5

**Comment by tastybento** [comment]
Understood. This is maybe the trickiest. I’d like to enable a way to include enchanted items in the chests which becomes more complex. Currently in the end for example you can find boots of falling.

**Comment by BONNe** [comment]
It is possible, just need a good enchant parser. 
I suggest something like original Minecraft use with /give command

**Comment by Poslovitch** [comment]
It should use the ItemParser from BentoBox

**Comment by tastybento** [comment]
ItemParser is unfortunately too basic. It can’t handle multiple enchants or complex lore. I do like the JSON string idea. Is there a built in API to parse that into an iteam?

**Comment by Poslovitch** [comment]
ItemParser can be improved. Or we can rely on a built in API, if it exists. Aren't ItemStacks serializable?

**Comment by tastybento** [comment]
Just to clarify I should use ItemParser but the code approach today is too weak. It needs improving to handle complex items.

**Comment by tastybento** [comment]
Item stacks are serializable but not easy to generate freehand and obscure. There are lots of tools on the web for the JSON one.

**Comment by tastybento** [comment]
So, the "JSON one" is called NBT (Notch Binary Tag)
https://www.spigotmc.org/threads/tutorial-using-nbt-with-items.181183/
https://github.com/I-Al-Istannen/MiniNBT

It'd get us into reflection and NMS if we use it though.

The default YAML serialization from Bukkit is sounding better.

**Comment by jstnf** [comment]
@tastybento 
Would it be too late to overhaul ItemParser so that it uses the same format as before (and thus won't break everything else) but also supports other item data?

**Comment by jstnf** [comment]
example:

Base format:
MATERIALID:QTY

Optional modules:
ENCH[<ENCHANT1>[<LEVEL>],<ENCHANT2>[<LEVEL>]]
DURA[<DURABILITY>]
LORE["<LORE1>","<LORE2>"]

etc...
BANNER[...]
FIREWORK[...]
LEATHERARMOR['COLOR[<COLOR>]'/'RGB[<RGB>]']
POTION[...]
SKULL[...]
SPAWNEGG[...]
TROPICALFISHBUCKET[...]

example items:
POTION:1:POTION[STRENGTH[1],EXTENDED,SPLASH]
POTION:POTION[SPLASH,STRENGTH[1],EXTENDED]:1
(these two are the same thing, demonstrating being able to change the order around)

DIAMOND_PICKAXE:DURA[100]:ENCH[DIG_SPEED[5],MENDING,SILK_TOUCH]:NAME["Amazing Pickaxe"]:1
Diamond Pickaxe w/ durability of 100, efficiency 5, mending, and silk touch, named "Amazing Pickaxe"

etc...

**Comment by tastybento** [comment]
@jstnf We went down that route with ASkyBlock and you will end up spending a lot of time on defining the syntax of these extra items and then maintaining the parsing code, especially when 1.14, 1.15 etc. come out with new items and capabilities. 

What I'm thinking now is that a GUI will be a better way to define the loot table. Just drag and drop in the loot you want and then sent the probability. Then admins can have exactly what they want in there and the objects is precisely defined.

**Comment by jstnf** [comment]
Ahh, so you’re going to deserialize from the ItemStack.

Now that you mention that, that’s probably the easiest solution.

**Comment by tastybento** [comment]
Instead of having custom loot settings, I added a setting in version 1.5.0 to add more items to the chest. This helps a lot. Watch out for lag though.
