### ISSUE TITLE
/sg help 

### ISSUE THREAD

**Issue by robert-beckley** [BentoBoxWorld/SkyGrid#9]
**Description**
/sg help prints the commands with the double skygrid:skygrid 

**Steps to reproduce the behavior:**
Type / Sg help
See issue

**Expected behavior**
For it to display like /is help, /ai help

**Screenshots**
![image](https://user-images.githubusercontent.com/41904721/52171985-be342700-27ba-11e9-9f2d-cb653b3e1f58.png)

**Extra Information:**

![image](https://user-images.githubusercontent.com/41904721/52171988-d0ae6080-27ba-11e9-85fb-fcb00605f486.png)

**Comment by tastybento** [comment]
I can't replicate right now. Hmm. Do you still see this?
<img width="686" alt="screen shot 2019-02-12 at 6 35 03 pm" src="https://user-images.githubusercontent.com/4407265/52682629-f4795100-2ef4-11e9-90e4-4f042ba50679.png">

**Comment by robert-beckley** [comment]
I think this was fixed in the dev build i have. I will check and confirm
